// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6iiLCSZ6JnkJB44ble9U5T23sZzgaVQA',
    appId: '1:989526758790:web:fec6f4b2f24428f8640807',
    messagingSenderId: '989526758790',
    projectId: 'gym-1-b82fc',
    authDomain: 'gym-1-b82fc.firebaseapp.com',
    storageBucket: 'gym-1-b82fc.firebasestorage.app',
    measurementId: 'G-2LMYTY0V78',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYU2MAxb-HrCA4uSWvdS-daaFrdBzsIIw',
    appId: '1:989526758790:android:1b43e9d516137c74640807',
    messagingSenderId: '989526758790',
    projectId: 'gym-1-b82fc',
    storageBucket: 'gym-1-b82fc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAopAqRpuUXqEx3Sd8jQTewVjCenqh8usA',
    appId: '1:989526758790:ios:db4878f30affea50640807',
    messagingSenderId: '989526758790',
    projectId: 'gym-1-b82fc',
    storageBucket: 'gym-1-b82fc.firebasestorage.app',
    iosBundleId: 'com.example.newStructure',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAopAqRpuUXqEx3Sd8jQTewVjCenqh8usA',
    appId: '1:989526758790:ios:db4878f30affea50640807',
    messagingSenderId: '989526758790',
    projectId: 'gym-1-b82fc',
    storageBucket: 'gym-1-b82fc.firebasestorage.app',
    iosBundleId: 'com.example.newStructure',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6iiLCSZ6JnkJB44ble9U5T23sZzgaVQA',
    appId: '1:989526758790:web:a7aeaf8962f8aaa4640807',
    messagingSenderId: '989526758790',
    projectId: 'gym-1-b82fc',
    authDomain: 'gym-1-b82fc.firebaseapp.com',
    storageBucket: 'gym-1-b82fc.firebasestorage.app',
    measurementId: 'G-2V4ZFQFXSH',
  );
}
